### ISSUE TITLE
Links is not working

### ISSUE THREAD

**Issue by skjha1** [ashishpatel26/500-AI-Machine-learning-Deep-learning-Computer-vision-NLP-Projects-with-code#16]
The links for many project list is not opening.

**Comment by shajeen** [comment]
To be more specific this below link does not work. 




1 | 180 Machine learning Project | is.gd/MLtyGk
-- | -- | --
2 | 12 Machine learning Object Detection | is.gd/jZMP1A
3 | 20 NLP Project with Python | is.gd/jcMvjB
4 | 10 Machine Learning Projects on Time Series Forecasting | is.gd/dOR66m
5 | 20 Deep Learning Projects Solved and Explained with Python | is.gd/8Cv5EP
6 | 20 Machine learning Project | is.gd/LZTF0J
7 | 30 Python Project Solved and Explained | is.gd/xhT36v
9 | 5 Web Scraping Projects with Python | is.gd/6XOTSn
10 | 20 Machine Learning Projects on Future Prediction with Python | is.gd/xDKDkl
11 | 4 Chatbot Project With Python | is.gd/LyZfXv
12 | 7 Python Gui project | is.gd/0KPBvP
13 | All Unsupervised learning Projects | is.gd/cz11Kv
14 | 10 Machine learning Projects for Regression Analysis | is.gd/k8faV1
15 | 10 Machine learning Project for Classification with Python | is.gd/BJQjMN
16 | 6 Sentimental Analysis Projects with python | is.gd/WeiE5p
17 | 4 Recommendations Projects with Python | is.gd/pPHAP8
18 | 20 Deep learning Project with python | is.gd/l3OCJs
19 | 5 COVID19 Projects with Python | is.gd/xFCnYi
20 | 9 Computer Vision Project with python | is.gd/lrNybj
21 | 8 Neural Network Project with python | is.gd/FCyOOf



@ashishpatel26

**Comment by skjha1** [comment]
Yes.

**Comment by shajeen** [comment]
@skjha1 Please check and confirm, as link are working. Could be IS.GD site issue.

**Comment by skjha1** [comment]
Yes! that is only the issue apart from is.gd others are working. They need to update the sortlink by using another website or give parent link.

**Comment by skjha1** [comment]
Yes! that is only the issue apart from is.gd others are working. They need to update the sortlink by using another website or update its parent link.

**Comment by ashishpatel26** [comment]
It's updated
