### ISSUE TITLE
Link Not visible

### ISSUE THREAD

**Issue by TheAbhishekraj** [ashishpatel26/500-AI-Machine-learning-Deep-learning-Computer-vision-NLP-Projects-with-code#33]
Hi ,
Can you support on the same as unable to see links for the 500+ projects.

**Comment by AVDHUTCHINTAN** [comment]
link not visible

**Comment by chintanckg** [comment]
Links not visible!

**Comment by Rupendra-S** [comment]
Hi I couldn't see the link to any project in the repo please check @ashishpatel26

**Comment by saisirisha1111** [comment]
link is not visible. Please resolve the problem...

**Comment by ashishpatel26** [comment]
Resolved

**Comment by ashishpatel26** [comment]
Resolved
